version: "3.9"

services:
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  db-manager:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080

  # client-server:
  #   build: .
  #   ports:
  #     - 3000:3000
  #     - 4000:4000
