[build]
  base = "client/"
  publish = ".next/"
  environment = { NEXT_PUBLIC_GRAPHQL_ENDPOINT = "https://kcv-server-test.herokuapp.com/graphql" }

[[plugins]]
  package = "@netlify/plugin-nextjs"