version: 2.1

orbs:
  node: circleci/node@4.5.1

parameters:
  run_workflow_server:
    type: boolean
    default: false

  run_workflow_client:
    type: boolean
    default: false

jobs:
  job_server:
    docker:
      - image: cimg/node:16.3.0

    working_directory: ~/root/server

    steps:
      - checkout:
          path: ~/server

      - node/install-packages:
          pkg-manager: yarn

      - run:
          name: Testing
          command: yarn test

      - run:
          name: Building
          command: yarn build

  job_client:
    docker:
      - image: cimg/node:16.3.0

    working_directory: ~/root/client

    steps:
      - checkout:
          path: ~/root

      - node/install-packages:
          pkg-manager: yarn

      - run:
          name: Testing
          command: yarn test

      - run:
          name: Building
          command: yarn build

      - run:
          name: Deploying
          command: yarn deploy

workflows:
  workflow_server:
    when: << pipeline.parameters.run_workflow_server >>
    jobs:
      - job_server

  workflow_client:
    when: << pipeline.parameters.run_workflow_client >>
    jobs:
      - job_client
