version: 2.1

orbs:
  node: circleci/node@4.5.1

jobs:
  # job-server:
  #   docker:
  #     - image: cimg/node:16.3.0

  #   working_directory: ~/server

  #   steps:
  #     - checkout
  #     - node/install-packages

  #     - run:
  #         name: Testing
  #         command: yarn test

  #     - run:
  #         name: Building
  #         command: yarn build

  job-client:
    docker:
      - image: cimg/node:16.3.0

    working_directory: ~/root/client

    steps:
      - checkout:
          path: ~/root

      - node/install-packages:
          pkg-manager: yarn

      - run:
          name: Testing
          command: yarn test

      - run:
          name: Building
          command: yarn build

      - run:
          name: Deploying
          command: yarn deploy

workflows:
  # workflow-server:
  #   jobs:
  #     - job-server

  workflow-client:
    jobs:
      - job-client
