name: Client CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - "client/**"

  workflow_dispatch:
  
defaults:
  run:
    working-directory: './client'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Install dependencies
      run: npm ci

    - name: Run the tests and generate coverage report
      run: npm test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

    - name: Build
      run: npm run build

#     - name: Deploy
#       run: |
#         git config --global user.name $user_name
#         git config --global user.email $user_email
#         git remote set-url origin https://${github_token}@github.com/${repository}
#         npm run deploy
        
#       env:
#         user_name: 'github-actions[bot]'
#         user_email: 'github-actions[bot]@users.noreply.github.com'
#         github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
#         repository: ${{ github.repository }}
